### ISSUE TITLE
JS and Python reader/writer for JabCode?

### ISSUE THREAD

**Issue by DonaldTsang** [jabcode/jabcode#1]
Is it possible to have JS webapp or library for generating and reading JabCode?  
Also, is it possible to have Python wrapper for the JabCode libraries?

**Comment by d-klein** [comment]
There are currently no plans to develop a dedicated FOSS JS library or python wrapper. As JabcodeReader/Writer are simple commandline programs, it is however not too difficult to wrap them for a web-application. See https://jabcode.org/ for a demonstration and/or playing with codes and encodings.
