### ISSUE TITLE
Publish source code of Android Barcode Reader App

### ISSUE THREAD

**Issue by Simulant87** [jabcode/jabcode#10]
There is a packaged .apk Android App provided implementing a bar code reader.

It would be nice to have to source code published (maybe in a separate repository) to better understand how the library can be used and re-used.

**Comment by jabcode** [comment]
This simple APK was just put there to give a way to read jabcode using smart phones. Now it is no longer needed, because the website jabcode.org works as a web-app on either android or ios phones.

**Comment by cyb3rko** [comment]
Hey @Simulant87,

I've started working on an Android wrapper library: https://github.com/cyb3rko/jabcode-android  
Unfortunately I'm currently using a workaround by passing an image file path rather than passing raw bytes. That's why the performance could be better.

Happy about contributions :)
