### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [jabcode/jabcode#12]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream") ⇒ [main](https://github.com/jabcode/jabcode/blob/8bbf75a7454d262857f933dd554fc15d3317c6a4/src/jabcodeReader/jabreader.c#L63)
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator") ⇒ [parseCommandLineParameters](https://github.com/jabcode/jabcode/blob/c2ff2fd6a48cbb720f8a48ed97146a5be2282b25/src/jabcodeWriter/jabwriter.c#L93)

**Comment by jabcode** [comment]
Yep, we will probably do that in the new version. The jabcode Reader and Writer have been written as examples of using the core library and therefore not all error handling were considered.

**Comment by elfring** [comment]
Would another constructive information be nicer?

**Comment by jabcode** [comment]
Unfortunatly we can not promise when this could be done, we are focusing on the development of the core library for the new version. The Reader and Writer are just usage examples.
