### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [jabcode/jabcode#14]
I would like to point out that identifiers like “[`_DETECTOR_H`](https://github.com/jabcode/jabcode/blob/04fbf3833dbd91c99f28db1f564b7a9a80fc4b93/src/jabcode/detector.h#L14 "Update candidate")” and “[`_JAB_H`](https://github.com/jabcode/jabcode/blob/04fbf3833dbd91c99f28db1f564b7a9a80fc4b93/src/jabcode/include/jabcode.h#L14 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by jabcode** [comment]
Thanks, I will change these in the new version. Hopefully I will have time for that, :-)

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
