### ISSUE TITLE
Is there a mediatype marker in this standard? If not, is there a need or a way to get this in?

### ISSUE THREAD

**Issue by mofosyne** [jabcode/jabcode#15]
This might seem like a weird concept, but while reading through the JAB and QR barcode standards... I noticed it supports marking the content as ECI or FCN1 

But the density of jab code does give some opportunity to store various file in this code, much like an NFC tag.

At the moment, if you want to encode a file in a QR... you typically have to do it as a URI e.g. `data:image/png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==`

This storing of binary data as ascii uri is horribly inefficient.

These are the mediatype I like to see supported
* CBOR : More efficient than ASCII JSON structured data
* NDEF : Piggybacking off the NFC tag standard, so we can consistently support features like contact details, wifi access codes in a consistent manner.

Keeping the option to specify mediatype as a string also allow for future flexibility (e.g. future encryption key format).

Just not sure how one would have binary payload in QR or JAB code distinguished as having a binary file, rather than just arbitrary binary data. Plus how would it handle being split over multiple barcodes (e.g. a long encryption key?)

----------

If this is left undefined... you end up with adhoc implementation of application interpretation as is currently happening in the QR barcode world, as you can see in https://github.com/zxing/zxing/wiki/Barcode-Contents .

**Comment by jabcode** [comment]
Thanks for your suggestions. In the current version, only encoding markers like ECI are defined, no application/mediatype markers are included, which are left to applications. Payload interpretation is totally determined by applications. This might be considered in the new version. 
Btw, binary payload can be identified as file when it contains a valid/known file signature.
