### ISSUE TITLE
Need man page for errors.

### ISSUE THREAD

**Issue by OfficialSpade000** [jabcode/jabcode#17]
Actually, I'm facing a lot of errors without having any man page. The `--help` command isn't enough to explain how to operate JAB code. It will be nice if you can add some man page.

**Comment by jabcode** [comment]
We will consider that when we have time. At the moment, please refer to the documentationf (https://jabcode.github.io/jabcode/) for more details.

**Comment by maclomhair** [comment]
Excuse me, but why is this issue closed? It does not seem resolved to me.
