### ISSUE TITLE
Comparison to other similar barcode

### ISSUE THREAD

**Issue by DonaldTsang** [jabcode/jabcode#2]
Requesting a comparison document comparing JabCode with:
- CRONTO sign [seee link](https://www.vasco.com/products/two-factor-authenticators/cronto/visual-transaction-signature.html)
- PM-Code [see link](http://pm-code.com/eng/)
- CobraKing [see link](https://github.com/quake0day/CobraKing)
- HCC2D [see link](https://ieeexplore.ieee.org/document/5679869/)
- Microsoft HCCB
- Ultracode [see link](https://github.com/bwipp/postscriptbarcode)

**Comment by confiks** [comment]
As far as I can see:
- CRONTO, PM-Code and HCCB and AuthPaper are proprietary. CRONTO has attracted some usage mainly by banks, PM-Code looks like vaporware, AuthPaper seems dead and HCCB is [dead](https://en.wikipedia.org/wiki/High_Capacity_Color_Barcode#Discontinuation).
- CobraKing seems to be a 2012 research project, unmaintained
- Ultracode is not high capacity
- HCC2D seems to be mainly academic exploration

Papers and results similar to HCC2D pop up periodically (i.e. [this](https://pdfs.semanticscholar.org/95c7/fe455a084b0f0ce9923e996652156c1f7998.pdf)), but unfortunately nobody has released any (experimental) source code. It quite frustrating. For example, AuthPaper implemented their solution on top of ZXing, but they never cared to contribute back. They apparently thought they could make some money out of it, but now that their venture is dead, their ZXing modification is in limbo as well.

From my one-hour research, that makes JAB Code the only actually FOSS implementation of a high capacity 'barcode'. If you know of other (FOSS) implementations, please let me know. 

I'm quite surprised JAB Code has existed for so long in a fairly production-ready state without attracting much attention. It deserves much more, looking at the rest of the field.

**Comment by d-klein** [comment]
There are currently no plans to create such a document. One main reason is, as @confiks pointed out that several projects are research prototypes, not fully specified, abandoned, targeting a very specific usage scenario, or proprietary. Hence, a comparison is not possible.

**Comment by DonaldTsang** [comment]
@confiks @d-klein Another good example is called "CQR Code-9" OR "CQR Code-5" http://gibis.unifesp.br/sibgrapi16/eproceedings/upload/technical/ts8/22.pdf

**Comment by DonaldTsang** [comment]
@confiks any news from AuthPaper?

**Comment by mykiimike** [comment]
> I'm quite surprised JAB Code has existed for so long in a fairly production-ready state without attracting much attention. It deserves much more, looking at the rest of the field.

@confiks yes it deserves much more.

**Comment by DonaldTsang** [comment]
@mykiimike perhaps we can give it the attention it needs through social media?

**Comment by marco-querini** [comment]
For those interested to colored qr codes, I have released an online HCC2D code generator here.
https://hcc2d.com/
