### ISSUE TITLE
Undefined reference to *

### ISSUE THREAD

**Issue by OfficialSpade000** [jabcode/jabcode#20]
When trying to run make I get this problem.

```C:\MinGW\bin/ld.exe: ../jabcode/build/libjabcode.a(image.o):image.c:(.text+0x75): undefined reference to `png_image_write_to_file'
C:\MinGW\bin/ld.exe: ../jabcode/build/libjabcode.a(image.o):image.c:(.text+0xf0): undefined reference to `png_image_begin_read_from_file'
C:\MinGW\bin/ld.exe: ../jabcode/build/libjabcode.a(image.o):image.c:(.text+0x173): undefined reference to `png_image_finish_read'
C:\MinGW\bin/ld.exe: ../jabcode/build/libjabcode.a(image.o):image.c:(.text+0x1e8): undefined reference to `png_image_free'
collect2.exe: error: ld returned 1 exit status
make: *** [bin/jabcodeWriter] Error 1```

I'm in windows.
(MinGW.org GCC-8.2.0-3) 8.2.0

**Comment by jabcode** [comment]
Under Windows you have to build the PNG lib and Z lib by yourself. The source codes can be downloaded from http://www.libpng.org and https://www.zlib.net/.
