### ISSUE TITLE
Can the jabcode library encode char * with null bytes ?

### ISSUE THREAD

**Issue by scroobius-pip** [jabcode/jabcode#21]
I'm trying to encode chunks of a binary file as jabcodes and scan them back again. The binary file could have null characters. How does this library handle this ?

**Comment by jabcode** [comment]
The jabcoder encoder will find the shortest way to encode the input data regardless its orginal representation. A binary file may be encoded as binary data, but can also probably be encoded using different modes defined by jabcode.
