### ISSUE TITLE
Largest amount of data that can still be processed by a camera

### ISSUE THREAD

**Issue by TheRedSpy15** [jabcode/jabcode#22]
I know I know.... this is a rather complicated question

What is the best configuration that produces the largest amount of data? All while making sure the camera on a high end phone would still be able to process it

And how much data would that theoretically be? 

I need to store 32,000,000 bits (not bytes)

However, this can be broken/divided up

**Comment by jabcode** [comment]
It would be recommended to divide the data into multiple symbols of small/middle sizes rather than using extreme big size symbols, but it certainly depends on the application and the printing quality and capture device.
