### ISSUE TITLE
question: version compatibility

### ISSUE THREAD

**Issue by maxkoryukov** [jabcode/jabcode#24]
@jabcode @Huajian Liu

I have a question regarding versioning.

You bumped the version, and the last version is **2.0.0**. I have the code, which uses **v1.0.0**. Will it be compiled successfully with the `libjabcode v2.0.0` ???

Related to this commit: d315eb934281e169b02e3ef4b23afd5ed4e79465

**Comment by jabcode** [comment]
The new version is not compatible with the old one, as in the commit message mentioned, it has new finder patterns, new metadata struction, and so on.
