### ISSUE TITLE
Support encoding from hex file or base64.

### ISSUE THREAD

**Issue by photony** [jabcode/jabcode#26]
Is it possible to make jabcodeWriter read a hex file and encode it to barcode?
I was trying to do it but it says 'Encoding data failed' and 'Creating jab code failed'.
Then I tried for base64 but it failed again.
Any help? If it can't encode a hex file then I guess I'll make something that does it though it might take a year.

**Comment by WaldBer** [comment]
Your input seems to be too long. (The error message will be adjusted to make it more meaningful for this case.) 
In fact, JAB code can also process hex data. Try it with a few characters and you can see its working. You can also compress your data beforehand to accommodate more than 3.5Kb in an single code. If you do not like to use compression, you still have the option to add more symbols with --symbol-number and thus add more data, where the JAB code takes up more space. See the help for details.

**Comment by photony** [comment]
I tried it and it work. jabcode just can't handle this large file of 5MB. I will now close the issue.
