### ISSUE TITLE
jabcodeWriter and Reader make error on mac

### ISSUE THREAD

**Issue by MGSDS** [jabcode/jabcode#28]
bill@MacBook-Pro jabcodeWriter % make
gcc jabwriter.o -L../jabcode/build -ljabcode -L../jabcode/lib -ltiff -lpng16 -lz -lm -O2 -std=c11 -o bin/jabcodeWriter
ld: warning: ignoring file ../jabcode/lib/libtiff.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
ld: warning: ignoring file ../jabcode/lib/libpng16.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
ld: warning: ignoring file ../jabcode/lib/libz.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
Undefined symbols for architecture x86_64:
  "_TIFFClose", referenced from:
      _saveImageCMYK in libjabcode.a(image.o)
  "_TIFFDefaultStripSize", referenced from:
      _saveImageCMYK in libjabcode.a(image.o)
  "_TIFFOpen", referenced from:
      _saveImageCMYK in libjabcode.a(image.o)
  "_TIFFSetField", referenced from:
      _saveImageCMYK in libjabcode.a(image.o)
  "_TIFFWriteScanline", referenced from:
      _saveImageCMYK in libjabcode.a(image.o)
  "_png_image_begin_read_from_file", referenced from:
      _readImage in libjabcode.a(image.o)
  "_png_image_finish_read", referenced from:
      _readImage in libjabcode.a(image.o)
  "_png_image_free", referenced from:
      _readImage in libjabcode.a(image.o)
  "_png_image_write_to_file", referenced from:
      _saveImage in libjabcode.a(image.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/jabcodeWriter] Error 1

**Comment by harieamjari** [comment]
Oh please!... Ommit this line from the make file `-L../jabcode/lib `.

The makefile is designed to work in a linux system. You should already know that.

If the problem continues comment me again. :)

**Comment by jabcode** [comment]
The precomplied libs libtiff.a and libpng.a are only for linux systems, you have to recompiel the libs on Mac by yourself, or just use the system libs by changing the Makefile as harieamjari said.

**Comment by sathishskein** [comment]
Undefined symbols for architecture arm64:
  "_png_image_free", referenced from:
      _readImage in image.o
  "_TIFFOpen", referenced from:
      _saveImageCMYK in image.o
  "_TIFFWriteScanline", referenced from:
      _saveImageCMYK in image.o
  "_TIFFSetField", referenced from:
      _saveImageCMYK in image.o
  "_png_image_finish_read", referenced from:
      _readImage in image.o
  "_TIFFDefaultStripSize", referenced from:
      _saveImageCMYK in image.o
  "_TIFFClose", referenced from:
      _saveImageCMYK in image.o
  "_png_image_begin_read_from_file", referenced from:
      _readImage in image.o
  "_png_image_write_to_file", referenced from:
      _saveImage in image.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by harieamjari** [comment]
@sathishskein build the library libpng libtiff and libz on your own. If you're in linux, that easy for yourself.

**Comment by harieamjari** [comment]
@sathishskein build the library libpng libtiff and libz on your own. If you're in linux, that easy for yourself.
