### ISSUE TITLE
Calculating the --symbol-version

### ISSUE THREAD

**Issue by harieamjari** [jabcode/jabcode#29]
In an example of argument `--symbol-number 4 --symbol-position  0 3 9 2`. What's the symbol version? How to figure it out? I can't seem to find the answer in the internet.

**Comment by jabcode** [comment]
The symbol version must be given by the argument "--version".

**Comment by harieamjari** [comment]
Never mind. I have solved it just by randomly picking some side version like this: 

`32 32 32 32 32 32 32 32`

Cheers!
