### ISSUE TITLE
More than 8 colors is broken

### ISSUE THREAD

**Issue by goblin** [jabcode/jabcode#30]
When trying to use `--color-number` greater than 8, the produced PNG file is unreadable by jabcodeReader (`JABCode Error: Too many errors in message. LDPC decoding failed.`), even if I use `--ecc-level 10`.

**Comment by jabcode** [comment]
The modes with more than 8 colors  are disregarded in the new development and may not work properly. They are changed to "reserved mode" in the new version.

**Comment by goblin** [comment]
OK, so you're dropping support for that feature. Can you give a reason why? I was particularly looking for something that could encode with multiple colours, to increase data storage density on paper...

**Comment by jabcode** [comment]
> OK, so you're dropping support for that feature. Can you give a reason why? I was particularly looking for something that could encode with multiple colours, to increase data storage density on paper...

The change is based on feedback from barcode practitioners, but you can still use more than 8 colors, it is just not strictly defined in the specification. For that you may have to adjust some part of the codes though.

**Comment by jabcode** [comment]
> OK, so you're dropping support for that feature. Can you give a reason why? I was particularly looking for something that could encode with multiple colours, to increase data storage density on paper...

The change is based on the requirement of ISO standard and feedback from barcode practitioners. ISO standard shall only include what works stably with current hardware and without restriction to the usage environment.  You can still use modes with more than 8 colors, they are just not strictly defined in the specification any more. For that you may have to adjust some part of the codes though.

**Comment by goblin** [comment]
Would you accept a patch that would "adjust" those parts of the source code to make it work?

**Comment by goblin** [comment]
> they are just not strictly defined in the specification any more

Which specification are you referring to? The one I can find at https://www.bsi.bund.de/EN/Publications/TechnicalGuidelines/TR03137/BSITR03137.html (linked from the README and jabcode.org) still refers to up to 256 colours.

**Comment by jabcode** [comment]
> Would you accept a patch that would "adjust" those parts of the source code to make it work?

It will be done later when I have time.

**Comment by jabcode** [comment]
> > they are just not strictly defined in the specification any more
> 
> Which specification are you referring to? The one I can find at https://www.bsi.bund.de/EN/Publications/TechnicalGuidelines/TR03137/BSITR03137.html (linked from the README and jabcode.org) still refers to up to 256 colours.

I meant the ISO draft.

**Comment by yao5461** [comment]
The same problem. How to enable 16 colors or 32 colors. : )

**Comment by maclomhair** [comment]
I cannot see a reason why this issue would be closed. AFAIK, more than 8 colors is still broken and a appropriate warning is displayed neither in the command line tools nor in the documentation.

I think this issue is thereby still unresolved and open.

**Comment by jabcode** [comment]
> I cannot see a reason why this issue would be closed. AFAIK, more than 8 colors is still broken and a appropriate warning is displayed neither in the command line tools nor in the documentation.
> 
> I think this issue is thereby still unresolved and open.

It is closed because the modes with more than 8 colors are not defined in the coming ISO standard and therefore they should not be included in the reference implementation. However, users can extend the implementation to support more colors as those modes are defined as "reserved mode" in the standard.
