### ISSUE TITLE
Is soft-decision LDPC decoding not used at all?

### ISSUE THREAD

**Issue by goblin** [jabcode/jabcode#32]
Grepping through code, it appears the `decodeLDPC()` function isn't used at all -- `decoder.c` only calls `decodeLDPChd()`. Does this mean the best feature of LDPC codes, soft-decision decoding, isn't used, and the codes are decoded using the inferior hard-decision decoding algorithm?

**Comment by jabcode** [comment]
In our tests, soft decoding did not work better in jabcode.

**Comment by goblin** [comment]
I was testing this on a definitely high-end CPU :-O

**Comment by goblin** [comment]
Oh, you probably meant other testing. So how can I re-enable it? Just change the calls to `decodeLDPC()` in decoder.c?

**Comment by jabcode** [comment]
> Oh, you probably meant other testing. So how can I re-enable it? Just change the calls to `decodeLDPC()` in decoder.c?

To enable soft decoding, the module decoding should be adjusted accordingly to output probability instead of bit values.

**Comment by goblin** [comment]
> Sure, soft-decoding has advantages, it is just temporarily disabled
> To enable soft decoding, the module decoding should be adjusted accordingly

OK, is there a previous version/commit where it worked? When you say "temporarily disabled" it suggests it used to work before.

**Comment by jabcode** [comment]
> > Sure, soft-decoding has advantages, it is just temporarily disabled
> > To enable soft decoding, the module decoding should be adjusted accordingly
> 
> OK, is there a previous version/commit where it worked? When you say "temporarily disabled" it suggests it used to work before.

A function for soft decoding of modules can be found in previous versions, but I am not sure in which one (maybe in versions before 2019). In the current development, only hard decoding (improved) is used. The improved soft decoding will be added in the future.

**Comment by goblin** [comment]
Cool, thanks for the info. I have a feeling that soft decoding could be more reliable when more colours are used, but I can't test that right now.
