### ISSUE TITLE
Error by running make command in src/jabcodeWriter or jabcodeReader

### ISSUE THREAD

**Issue by sathishskein** [jabcode/jabcode#33]
Undefined symbols for architecture arm64:
"_png_image_free", referenced from:
_readImage in image.o
"_TIFFOpen", referenced from:
_saveImageCMYK in image.o
"_TIFFWriteScanline", referenced from:
_saveImageCMYK in image.o
"_TIFFSetField", referenced from:
_saveImageCMYK in image.o
"_png_image_finish_read", referenced from:
_readImage in image.o
"_TIFFDefaultStripSize", referenced from:
_saveImageCMYK in image.o
"_TIFFClose", referenced from:
_saveImageCMYK in image.o
"_png_image_begin_read_from_file", referenced from:
_readImage in image.o
"_png_image_write_to_file", referenced from:
_saveImage in image.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Error by running make command in src/jabcodeWriter or jabcodeReader

**Comment by harieamjari** [comment]
You should build the libpng libtiff (libz) for you operating system.

If you are in windows then that would be  easy peasy. Just download my jabcode fork and replace those lib with the lib in the folder win64 then run `make`.

**Comment by harieamjari** [comment]
You could also just download the compiled software from my fork.

**Comment by shatterhand19** [comment]
@harieamjari I tried it and it is saying that they are incompatible. Where did you find the source code to build yourself?

**Comment by harieamjari** [comment]
I added a new lib to solve the problem that causes the error, "could not find *.dl". The windows release should be working again.

**Comment by jabcode** [comment]
> You should build the libpng libtiff (libz) for you operating system.
> 
> If you are in windows then that would be easy peasy. Just download my jabcode fork and replace those lib with the lib in the folder win64 then run `make`.

Thanks for the answer and a guildline of building Windows DLL is added.
