### ISSUE TITLE
Android reader question.

### ISSUE THREAD

**Issue by harieamjari** [jabcode/jabcode#35]
Hi, I have tried installing the 'android reader apk', but may I ask what it really does? It does not read the jabcode when I tried it.

**Comment by harieamjari** [comment]
JabCodeApp.apk is not working anymore. There was a problem parsing the package.

**Comment by jabcode** [comment]
It works well on our test phones like Samsung S9 and Huawei Mate9. Anyway, a new version will be uploaded soon with the recent updates.

**Comment by harieamjari** [comment]
I tried installing it in a different android and its now running. I tried pointing my camera to the data-matrix created by jabcode and it seems to do nothing. Am I missing something here?

**Comment by jabcode** [comment]
> I tried installing it in a different android and it's now running. I tried pointing my camera to the data-matrix created by jabcode and it seems to do nothing. Am I missing something here?

You may start with a simple default 8-color code, e.g. Version 1 or 2, to test if the App works properly.
