### ISSUE TITLE
Is jabcode right for my project?

### ISSUE THREAD

**Issue by affluent-bilby-classifieds** [jabcode/jabcode#36]
I am developing a (off-line) classified paper that uses the yclas (open classifieds) database. The purpose of this paper is to ensure that people without access to a computer can still have access to classified and employment ads. Python scripts will auto generate the entire paper in LaTeX. 
Although they may not have access to a computer many of them will still have a smart-phone. I plan to include something like a (as tiny as possible while still workable) data barcode. I have been researching, QR codes, micro QR codes, iQR codes and all come with their advantages and disadvantages. I have put in the command line I have used below. http://klas.local/1 is using the "YOURLS" URL shortener but it was still too long for a MicroQR code.  The link takes them to an expanded listing on yclas with photos and even updates with sold or unsold status.

./jabcodeWriter --input 'http://klas.local/1' --output 1.png --symbolc-number 30 --color-number 4 --symbol-width 50 --symbol-height 50

Any smaller than that and it doesn't seem to be able to read the jab-code with the Android app on my Xiaomi mi m8 reading from my screen with white background "print preview". Perhaps bleed becomes an issue when working with colors at such small sizes?

This project looks really good  and I especially like how it is under active development. I believe that jab-code has a very bright and colorful future.
 
Here is the github link to my project if you want to take a look. The jab-code was just entered as postscript as there isn't currently a LaTeX or PST-Tools extension for jab-code.

https://github.com/affluent-bilby-classifieds/jinjalatex

Something I just thought of today. If I can make a horizontal line Jabcode that might be suitable for my project as there needs to be a line anyway between each classified ad. Why not encode data in it?

As long as jab-code can have some kind of tolerance to a line of text perhaps there could be a rectangular jab-code for each category or sub-category heading that contains a base-url and then the rest of the short url code comes up in a jab-code for each individual classified ad. The four corners of each ad could help the android app find it's location similar to how QR codes work.

**Comment by affluent-bilby-classifieds** [comment]
I watched a youtube video on Jab-code. (https://www.youtube.com/watch?v=U0G9xxZ8Fg0)

It seems it can do what I want, however, I am unsure how to generate what I am looking for with the current version of the Jabcode writer.

**Comment by harieamjari** [comment]
I have tried installing the android jabcode and trying to decode some jabcode, but it doesn't seem to work. Maybe it's a bug? That's why I have issued the issue 'Android reader question' found right below your issue.

**Comment by affluent-bilby-classifieds** [comment]
Closing as this topic is stale and I have moved onto other projects.
