### ISSUE TITLE
How soon will the ISO standard be published?

### ISSUE THREAD

**Issue by Manaka-Nemu** [jabcode/jabcode#37]
I am programming my own barcode generators for the calculator. I like your project and of course I want to programming it in the calculator. But I can't understand how the LDPC be encoded (Many of the other 2D codes use RS). The example in the released technical specification is rough, and the tutorials I found in the internet is so hard to amateurs. Hope that the ISO can make it easier to understand.
This project has a very bright future. I'm very glad to see its developing.

**Comment by harieamjari** [comment]
In my opinion, an International Standard would be made if it's needed in the market. An ISO standard must be needed in the market. In the meantime, they [The developer] have some pdf explaining the gists of it.

**Comment by jabcode** [comment]
The iso standardization is ongoing, it's hard to estimate how long it will take.

**Comment by harieamjari** [comment]
> The iso standardization is ongoing, it's hard to estimate how long it will take.

I hope the ISO standard for jabcode is free and can be freely distribute. Please make it free (if possible).

**Comment by Manaka-Nemu** [comment]
> > The iso standardization is ongoing, it's hard to estimate how long it will take.
> 
> I hope the ISO standard for jabcode is free and can be freely distribute. Please make it free (if possible).

Ditto.

**Comment by jabcode** [comment]
> > The iso standardization is ongoing, it's hard to estimate how long it will take.
> 
> I hope the ISO standard for jabcode is free and can be freely distributed. Please make it free (if possible).

I think it can not be decided by us.

**Comment by hvitis** [comment]
What does it mean that ISO standard can perhaps not be free? Does it mean that we won't be able to utilize this library or technology itself?

**Comment by harieamjari** [comment]
> What does it mean that ISO standard can perhaps not be free? Does it mean that we won't be able to utilize this library or technology itself?

The library is license under LGPL-2.1, so its source code must be distributed freely.

Most ISO standard are not freely available and must be bought with cash.

Take for example the ISO 18004:

> The ISO/IEC 18004:2015 defines the requirements for the symbology known as QR Code. It specifies the QR Code symbology characteristics, data character encoding methods, symbol formats, dimensional characteristics, error correction rules, reference decoding algorithm, production quality requirements, and user-selectable application parameters.

Or simply, the ISO 18004 describes what a QR code is made of.

**Comment by mohana-martin** [comment]
For any one interested, there is a bit of specification in [BSI TR 03137 – Part 2 JAB Code (Just Another Bar Code)](https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TR03137/BSI-TR-03137_Part2.pdf), but as is mentioned on the [landing page](https://www.bsi.bund.de/EN/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03137/tr03137_node.html) of this document;

> Changes that are established during the standardization process are not part of this specification

Not sure how big the changes are, and whether @jabcode could indicate the delta's to help their work to get actually adopted by the world, but at least the BSI-TR-03137 Part 2 gives a hint on the inner working.

**Comment by asdfjkl** [comment]
Jabcode has been standardized under ISO a long time ago: https://www.iso.org/standard/76478.html

The specification in BSI TR 03137 – Part 2 and ISO 23634:2022 differ!

**Comment by mohana-martin** [comment]
I know that the standard has been published 2 or so years ago. However, placing the specification inside a standard that is behind a 200 EUR paywall, for something that has been developed (partially) using public money, is a bit absurd. This, especially, when you also strive for it to become widely adopted. But that's just my two cents.
