### ISSUE TITLE
What did I do wrong?

### ISSUE THREAD

**Issue by jab-code** [jabcode/jabcode#39]
Hi, I followed exactly the build instructions, with the same Ubuntu version, same gcc version, same GNU make version.
But in the folder bin where the app is generated, when I write:
```
~/Downloads/jabcode-master/src/jabcodeWriter/bin$ jabcodeWriter --help
```
It says:
```
jabcodeWriter: command not found.
```
Any ideas please?

**Comment by RCasatta** [comment]
try with `./jabcodeWriter --help`
note the `./` at the beginning of the line (means current directory)

**Comment by jab-code** [comment]
Thank you a lot @RCasatta 😊
