### ISSUE TITLE
android reader source code

### ISSUE THREAD

**Issue by murdak** [jabcode/jabcode#41]
Hi

I'm curious how the android reader app auto captures a jabcode.
Is there a pattern recognition involved? 
If so, what libraries do you recommend? 

Thanks.

**Comment by xaverdh** [comment]
Yes, please publish the source code for the apk.

**Comment by jabcode** [comment]
> Hi
> 
> I'm curious how the android reader app auto captures a jabcode.
> Is there a pattern recognition involved?
> If so, what libraries do you recommend?
> 
> Thanks.

In the current version the app just takes photos and the jabcode library does the rest.

**Comment by murdak** [comment]
> > Hi
> > 
> > I'm curious how the android reader app auto captures a jabcode.
> > Is there a pattern recognition involved?
> > If so, what libraries do you recommend?
> > 
> > Thanks.
> 
> In the current version the app just takes photos and the jabcode library does the rest. 


I see.

The captured preview is directly fed into jabcode reader but i see that reader works with png data.
If I remember correctly, camera preview returns bitmap. Is bitmap converted internally by the reader?

**Comment by jabcode** [comment]
> > > Hi
> > > I'm curious how the android reader app auto captures a jabcode.
> > > Is there a pattern recognition involved?
> > > If so, what libraries do you recommend?
> > > Thanks.
> > 
> > 
> > In the current version the app just takes photos and the jabcode library does the rest.
> 
> I see.
> 
> The captured preview is directly fed into jabcode reader but i see that reader works with png data.
> If I remember correctly, camera preview returns bitmap. Is bitmap converted internally by the reader?

No conversion is needed, you don't have to use the reader. The captured bitmap can be directly fed into the core library.

**Comment by murdak** [comment]
> > > > Hi
> > > > I'm curious how the android reader app auto captures a jabcode.
> > > > Is there a pattern recognition involved?
> > > > If so, what libraries do you recommend?
> > > > Thanks.
> > > 
> > > 
> > > In the current version the app just takes photos and the jabcode library does the rest.
> > 
> > I see.
> > 
> > The captured preview is directly fed into jabcode reader but i see that reader works with png data.
> > If I remember correctly, camera preview returns bitmap. Is bitmap converted internally by the reader?
> 
> No conversion is needed, you don't have to use the reader. The captured bitmap can be directly fed into the core library.

would it be possible to show a gist or a snippet of this?

currently, what i do on Android side is write captured image as png image file then pass file path to native to be processed as file input for jabcode reader just like command line parameter. but it's not very efficient.

i can changed and passed a bytearray of png/bitmap image from camera preview but setting it as jbitmap crashes the app.

**Comment by jabcode** [comment]
You don't have to set it as jbitmap, just pass jbyteArray to the jni.

**Comment by murdak** [comment]
Here's a [gist](https://gist.github.com/murdak/5de5b4715d9dc74a4ed6459db2ca94ad) of the code I use for decoding:

Which gives me this error when app crashes:
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x79c4600000 in tid 5883

**Comment by jabcode** [comment]
The pixel buffer of a jab_bitmap stores the raw RGB values instead of a png. The preview bitmap should not be converted into png.

**Comment by murdak** [comment]
you are absolutely right.
it works now. 
thanks.

**Comment by cyb3rko** [comment]
@murdak @jabcode  
Hey guys, I'm finally working on an Android library to easily include JAB Codes into Android apps.  
I'm currently stuck on passing the `jbyteArray` to the library.

If I'm not completely off the library expects a `jab_bitmap*` as parameter to find the JAB code.  
So my question now is how to pass my `jbyteArray` as a `jab_bitmap*`?

Thanks for your help

**Comment by cyb3rko** [comment]
A first version of the Android wrapper library is finally finished: https://github.com/cyb3rko/jabcode-android  
Unfortunately I'm currently using a workaround by passing an image file path rather than passing raw bytes. That's why the performance could be better.

Happy about contributions :)
