### ISSUE TITLE
Feauture request. Piping.

### ISSUE THREAD

**Issue by harieamjari** [jabcode/jabcode#42]
Would it be possible to directly used the stdin as an input file? That would be convenient  to other user such that they can only type, 

`cat file | ./jabcodeWriter`

Of course, the stdin will be the default when `jabcodeWriter` has no arguments (like one above) or has no input file but has a configuration (like one below):
`cat file | ./jabcodeWriter --color-number 16`

Some tips into implementing this is that you might need to reopen stdin in "rb" mode.

**Comment by harieamjari** [comment]
Oh! and we could discuss the pros and cons of having this feature implemented (if there's any).

**Comment by jabcode** [comment]
This feature was implemented in a test code during testing but not inclued in the writer. We can try to put the snippet in the writer.

**Comment by harieamjari** [comment]
Non topic aside, as I went to look at the source code, trying to set `fp = stdin`, I read something that must be address:

https://github.com/jabcode/jabcode/blob/9fe02417e258dfd112a6096b88d22931839917b9/src/jabcodeWriter/jabwriter.c#L103-L104

According to C standard:

```
Setting the file position indicator to end-of-file, as with fseek(file, 0, SEEK_END), has undefined behavior for a
binary stream (because of possible trailing null characters) or for any stream with state-dependent encoding that does not
assuredly end in the initial shift state.
```
https://port70.net/~nsz/c/c11/n1570.html#note268

Here's a question to this problem in SO https://stackoverflow.com/questions/49121638/use-ftell-to-find-the-file-size

But still, It's also what I would use because it does seem to work.
