### ISSUE TITLE
Always LDPC decoding failed when using --color-number 16 or more

### ISSUE THREAD

**Issue by ffgpu-org** [jabcode/jabcode#43]
I use "jabcodeWrite --color-number 16 --symbol-version 32 32 --input-file input.data --output out.png" is OK.
But when decoding using "jabcodeReader out.png --output out.data" is ERROR! It report "Too many errors in message. LDPC decoding failed."

Using --color-number 8 is OK.

**Comment by jabcode** [comment]
The current version only supports 4 colors and 8 colors, the default color number is 8. Please refer to [this issue](https://github.com/jabcode/jabcode/issues/30).
