### ISSUE TITLE
Building library dependencies 

### ISSUE THREAD

**Issue by murdak** [jabcode/jabcode#47]
What versions of the dependencies are recommended?

libz - 1.2.11?
libpng16 - 1.6.37?
libtiff- 4.1.0?
libjpeg - jpeg-9d?

any other dependencies? 

I want to build a jabcode shared library on Ubuntu to be loaded by another application (for now a basic command line app). And so I converted the reader and writer into one shared library.

**Comment by jabcode** [comment]
I believe it works with all latest versions.

**Comment by murdak** [comment]
> I believe it works with all latest versions.

Adding the CFLAG - fPIC fixed it.
Thanks.
