### ISSUE TITLE
Creating & reading L shaped codes.

### ISSUE THREAD

**Issue by hvitis** [jabcode/jabcode#52]
I have found information in the documentation that the code produced does not have to be square shaped in order to produce the reading. There is an example of L shaped one on page 33 of the [document][0].

It seems like the official reader on the page does not support the encoding of those. Where could I generate example L shaped codes? How would I go about it?

Thank you

[0]: https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TR03137/BSI-TR-03137_Part2.pdf;jsessionid=6D7AA976AEDCDA3EF3F4407C87AFFDB9.2_cid502?__blob=publicationFile&v=3

**Comment by jabcode** [comment]
The easiest way is to use jabcode.org, where you can generate codes with arbitrary shapes.

**Comment by hvitis** [comment]
@jabcode thank you! I missed the fact that Layout offers possibility of adding adjacent layers. Sorry!
