### ISSUE TITLE
Audio files in JAB

### ISSUE THREAD

**Issue by hvitis** [jabcode/jabcode#54]
I'm sorry if this sounds a bit trivial. I've checked the documentation and table with allowed characters for encoding and I was wondering if it would be possible to encode an audio file in the JAB code/image_

**Comment by jabcode** [comment]
Yes, that's possible. Either binary or text file can be encoded in JAB code. You can use the argument '--input-file' in jabcodeWriter for encoding and use the argument '--output' in jabcodeReader for decoding.

**Comment by harieamjari** [comment]
Correct me if I'm wrong; Jabcode can encode any arbitrary binary files or text files, but there is a limit on the size of these files.

An algorithm specifically designed to encode a waveform on a barcode would be efficient, and might encode more time. Though I believe using a compressed file format like mp3 would work than trying to invest time inventing such kind of algorithm.

**Comment by hvitis** [comment]
You're right. The same way as compression using algorithm that flexibly matches human thoughts, voice intonation etc would compress voice better that aac or mp3.

Back to the JAB audio topic. The provided app reads text without problem. I tested it and it works great. My question is: 

**What would a process of decoding audio from JAB code by mobile app look like? ** 

What's necessary on this case? Extra libraries and pure Android development? New algorithm? Adjusting existing app? 

Thank you!

**Comment by jabcode** [comment]
The App is just a demo, it does not support saving the decoded data as a file. If you want to decode audio on smart phones, you have to write your own app which can save the decoded audio as a file or a stream.

**Comment by hvitis** [comment]
@jabcode Thank you for all the guidance. I started with decoding the apk and will upload my findings in another android related issue.

As per audio files I have encoded an image with my voice inside using Ubuntu 14.04 node on Linode and decoded it with success. Your invention is truly amazing and breaking boundaries. I will work on Android decoder to hear the voice from printed image. This way our descendants will be able to listen to us when looking on our pictures in hundreds of years. Thank you to all great minds that have developed this algorithm. 

![my_voice](https://user-images.githubusercontent.com/17104239/106494722-0cb85100-64bb-11eb-805d-89be2b949565.png)

**Comment by Pixeldweller** [comment]
Wow, this sounds amazing. I'm gonna test something likewise with that when I have the time, too. I definitively wanna know the limits on this, even if the audio will be super compressed.

-- Imagine encoding voice messages or tonal comments on official printed documents. (I know that is a weird and unrealistic uncommon usecase, but it actually could be used as an creative innovation for E-Government!)
