### ISSUE TITLE
https://jabcode.org down?

### ISSUE THREAD

**Issue by Pixeldweller** [jabcode/jabcode#55]
Your [main](https://jabcode.org) website is down or misconfigured?

--- 
It would be a shame to see the project die down just like that. (Especially, when trying to convince Stakeholders to invest/care about this technology. I mean QR- and other Barcodes are still the norm, but encoding public keys with a simple jab is quite a nice feature.)

Any information on it, please?

**Comment by jabcode** [comment]
Thank you for the hint. It is fixed now. The error was from the last update. It was not noticed by me due to local cache.

**Comment by Pixeldweller** [comment]
Awesome! :)
