### ISSUE TITLE
Color variety of modules

### ISSUE THREAD

**Issue by hvitis** [jabcode/jabcode#56]
Hello!

I have been experimenting with encoding large sets of data for android app recognition and wanted to increase the amount of colors used in encoding. The provided app has a limit of 8. I have found an old closed topic on this but I have a question regarding it:

How can I achieve more than 8 colors in encoding? What should I change the C source code myself? The old topic mentions a special setting that could be triggered to allow encoder to work - is it still viable?

I have read the paper "A Versatile Polychrome 2D Barcode" and noticed information about office printer limitation. Nevertheless adding more colors should generate codes that are printable on specific printers that would provide necessary robustness. I am not limited by the environment therefore asking about how to achieve the color variety.

Thank you so much

**Comment by jabcode** [comment]
Yes, you have to adapt the source code by yourself. Some functions/definitions in the source code are not updated along with the changes in ISO specificatoin, since the modes with more than 8 colors are not defined in the coming ISO standard. Please refer to my answers in [this issue](https://github.com/jabcode/jabcode/issues/30).

**Comment by hvitis** [comment]
@jabcode Thank you! Sincerely.

**Comment by hvitis** [comment]
One more question (Sorry for reopening.)

Is Android decoder from the repo adjusted for >8 colors decoding?

**Comment by jabcode** [comment]
> One more question (Sorry for reopening.)
> 
> Is Android decoder from the repo adjusted for >8 colors decoding?

No, the Android App uses the same jabcode lib.
