### ISSUE TITLE
Test Mode

### ISSUE THREAD

**Issue by jbirbal-skydom** [jabcode/jabcode#67]
I've been trying to get the test mode option working for the past couple weeks. I've tried to do it using the CFLAG option:
`make CFLAGS=-DTEST_MODE=1`
AND also redefining the macro in detector.h

I'll get the following error each time: 
`gcc binarizer.o decoder.o detector.o encoder.o image.o interleave.o ldpc.o mask.o pseudo_random.o sample.o transform.o -L./lib/win64 -ltiff -lpng16 -lz -lm -shared -DTEST_MODE=1 -o build/libjabcode.dll
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: detector.o:detector.c:(.bss+0x0): multiple definition of "test_mode_bitmap"; decoder.o:decoder.c:(.bss+0x0): first defined here   
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: detector.o:detector.c:(.bss+0x8): multiple definition of "test_mode_color"; decoder.o:decoder.c:(.bss+0x8): first defined here    
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: encoder.o:encoder.c:(.bss+0x0): multiple definition of "test_mode_bitmap"; decoder.o:decoder.c:(.bss+0x0): first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: encoder.o:encoder.c:(.bss+0x8): multiple definition of "test_mode_color"; decoder.o:decoder.c:(.bss+0x8): first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ldpc.o:ldpc.c:(.bss+0x0): multiple definition of "test_mode_bitmap"; decoder.o:decoder.c:(.bss+0x0): first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ldpc.o:ldpc.c:(.bss+0x8): multiple definition of "test_mode_color"; decoder.o:decoder.c:(.bss+0x8): first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: mask.o:mask.c:(.bss+0x0): multiple definition of "test_mode_bitmap"; decoder.o:decoder.c:(.bss+0x0): first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: mask.o:mask.c:(.bss+0x8): multiple definition of "test_mode_color"; decoder.o:decoder.c:(.bss+0x8): first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: sample.o:sample.c:(.bss+0x0): multiple definition of "test_mode_bitmap"; decoder.o:decoder.c:(.bss+0x0): first defined here       
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: sample.o:sample.c:(.bss+0x8): multiple definition of "test_mode_color"; decoder.o:decoder.c:(.bss+0x8): first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: transform.o:transform.c:(.bss+0x0): multiple definition of "test_mode_bitmap"; decoder.o:decoder.c:(.bss+0x0): first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: transform.o:transform.c:(.bss+0x8): multiple definition of "test_mode_color"; decoder.o:decoder.c:(.bss+0x8): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:10: build/libjabcode.dll] Error 1`

What DID worked for me was hard coding the test mode value in detector.h and relocating the following code to detector.c  e.g.
` #if TEST_MODE
jab_bitmap* test_mode_bitmap;
jab_int32	test_mode_color;
#endif `

I also had to create a sample.h with: 

`#include "./include/jabcode.h"
#include "detector.h"
#if TEST_MODE
extern jab_bitmap* test_mode_bitmap;
extern jab_int32	test_mode_color;
#endif`

but there must be an easier way to accomplish this. 

My goal is to use JabCode in the AR world. Anyone wants to hop on this project let me know. I have high faith in JabCode and the future of AR/VR with it. 

If this helps anyone here is the branch: 
https://github.com/jbirbal-skydom/jabcode/tree/Test

@jabcode please help enable test mode.

**Comment by jabcode** [comment]
Have you commented out the definition in detector.h?

**Comment by rishabhkus** [comment]
can anyone tell me how to access the test mode, I have just simply compiled that code and using executable on the Linux. which have only have simple command, I want to store binary data and do some kind of experiments.

**Comment by jbirbal-skydom** [comment]
No, I just started to work on it again. Still getting the same errors that the of multiple definition of `test_mode_bitmap'.

**Comment by jbirbal-skydom** [comment]
So I figured out what I had to do.... I anyone is curious  add this to detector.h


``` c
#ifndef TEST_MODE
#define TEST_MODE			0
#else
static jab_bitmap* test_mode_bitmap;
#endif
```


compile with CFLAG -DTEST_MODE


I use CMake so I'll upload the code on my repo
