### ISSUE TITLE
jab code library for android 

### ISSUE THREAD

**Issue by droid-at-help** [jabcode/jabcode#68]
I tried to decompile the apk but I didn't get the  source code. I wanna use jabcode for my android project can u send android lib.

**Comment by jabcode** [comment]
A customized lib for your android version can be compiled from the source code using NDK, either in Android Studio or using the toolchain provided by NDK. You can find many tutorials on the web about how to compile C code for android.

**Comment by droid-at-help** [comment]
source code is getting corrupted every time when I decompile the android app. Please can you tell me how to do it

**Comment by jabcode** [comment]
I mean the source code of the jabcode library, not the source code of the app.

**Comment by droid-at-help** [comment]
Can you send the android lib directly? that would be a great help

**Comment by jabcode** [comment]
sure, here you go.
[libBarcodeScanner.zip](https://github.com/jabcode/jabcode/files/8380220/libBarcodeScanner.zip)

**Comment by droid-at-help** [comment]
how to add in  the gradle build ?? bcz in github their is no instruction for gradle build

**Comment by jabcode** [comment]
> how to add in the gradle build ?? bcz in github their is no instruction for gradle build

It is well explained in the user guide of Android Studio, please refer to [this page](https://developer.android.com/studio/projects/gradle-external-native-builds)

**Comment by cyb3rko** [comment]
Hey @droid-at-help.  
How far have you got with your implementation?

I've started working on an Android wrapper library: https://github.com/cyb3rko/jabcode-android  
Unfortunately I'm currently using a workaround by passing an image file path rather than passing raw bytes. That's why the performance could be better.

Happy about contributions :)
