### ISSUE TITLE
Please consider using a color strategy

### ISSUE THREAD

**Issue by alexwykoff** [jabcode/jabcode#7]
The current system utilizes the whole range of colors for the purpose of information density.
While that works for computers, the human eye requirements are a bit different.

This is a fundamental tradeoff which hopefully makes sense in the broader context of human use of jabcodes.  One would hope that people print out the codes and put them on stickers, use them for shipping packages, introductions, or funny little bits of graffiti.  In a digital space, there could be image boards filled with these.  

One can imagine a wall or computer screen full of these dense pixel images and the incredible amounts of clashing colors, undoubtedly a human will be encouraged to look away.  

If the project choses to incorporate palettes, this will certainly facilitate broader adoption.
https://color.adobe.com/create/color-wheel is an excellent place to start.  Perhaps a triad or compound harmony would suffice for information needs?

**Comment by JakeTherston** [comment]
I think colors are required by the JABCODE spec to be as far from each other as possible (see Annex F of BSI TR 03137 – Part 2, page 62).

**Comment by DonaldTsang** [comment]
There are only 8 colors: RGB+white, CMYK.

**Comment by jabcode** [comment]
In Annex F, color selection up to 256 colors is given. See page 62, (a)-(g).
