### ISSUE TITLE
jabcodewriter build error: `'.rodata.str1.1' can not be used when making a PIE object``

### ISSUE THREAD

**Issue by anoduck** [jabcode/jabcode#77]
Attempted to compile jabcodewriter build with a simple `make`, as this is assumed to be the method for compilation. The result was a build error thrown in `../jabcode/lib/libtiff.a` and states:
```bash
/usr/bin/ld: ../jabcode/lib/libtiff.a(tif_close.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
```

This was assumed to be an error regarding the compilation of the tiff feature, so on the next build the tiff flag was removed from the gcc command string. `gcc jabwriter.o -L../jabcode/build -ljabcode -L../jabcode/lib -lpng16 -lz -lm -O2 -std=c11 -o bin/jabcodeWriter`. This resulted in a similar error message.

```bash
/usr/bin/ld: ../jabcode/lib/libpng16.a(png.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
```

Which is the same error as previous, except it concerns the png lib rather than the tiff lib. At this point, further attempts at compilation were paused until this issue could be reported.

**Comment by mallardtheduck** [comment]
I had this issue too; fixed it by removing the "-L../jabcode/lib" argument from the command in the Makefile and ensuring I had the libpng, libtiff and zlib development libraries installed on my system. It's pretty bad practice to have those libraries in binary from in the repo...

**Comment by anoduck** [comment]
@mallardtheduck Look at us, two birds of a feather! Visit any interesting ponds lately? 

Appreciate the response, as it built successfully after those extra parameters were removed, and it makes perfect sense now, the Makefile was expecting those libraries to be locally available. Goes to show, two ducks are better than one.

Cheers.
