### ISSUE TITLE
Cannot scan generated JAB Code with https://jabcode.org/scan

### ISSUE THREAD

**Issue by UniQP** [jabcode/jabcode#8]
Steps to reproduce:
1. `jabcodeWriter --input 'Test' --output test.png`
2. Goto https://jabcode.org/scan and scan the generated `test.png`

Expected behavior:
- Website shows message `Test`

Actual behavior:
- Website gives error message `No message has been found`

Version:
- `jabcodeWriter (Version 1.0.0 Build date: Nov 23 2018) - Fraunhofer SIT`
- 24b8cc2cb2d07eab10b53b161d58bbb406b4e032

**Comment by jabcode** [comment]
The website jabcode.org uses a new version under development, which includes new features and is not compatible with the one on github.

**Comment by jbartlau** [comment]
Will the sources here on GitHub be updated in a timely manner then? Will this update include breaking changes?

**Comment by jabcode** [comment]
Yes, when the changes of specification are finished, the source code here will be accordingly updated. We don't want to put interim source codes, which will cause more confusion. The version on jabcode.org will be updated more often for testing.
